include:
  - project: gitlab-org/frontend/untamper-my-lockfile
    file: templates/merge_request_pipelines.yml
  - project: gitlab-org/frontend/frontend-build-images
    file: /semantic-release/.gitlab-ci-template.rules.yml
  - component: ${CI_SERVER_FQDN}/gitlab-org/components/danger-review/danger-review@1.2.0

.svgs:is-design-gitlab-com-default-branch: &svgs-is-design-gitlab-com-default-branch
  if: !reference [.is-design-gitlab-com-default-branch, if]

.svgs:is-design-gitlab-com-mr: &svgs-is-design-gitlab-com-mr
  if: !reference [.is-design-gitlab-com-mr, if]

.svgs:node:
  image: node:20.19.5-bookworm
  cache: &global_cache
    paths:
      - packages/gitlab-svgs/node_modules
    policy: pull
  before_script:
    - cd packages/gitlab-svgs
    - yarn install --frozen-lockfile

svgs:build-and-check:
  extends:
    - .svgs:node
  stage: build
  needs: []
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - bash ./build_scripts/build-svgs.sh
    - echo "Starting Checks"
    - bash ./build_scripts/svg-lint.sh
  artifacts:
    paths:
      - packages/gitlab-svgs/dist

.svgs:pages:
  extends:
    - .svgs:node
  stage: deploy
  needs:
    - svgs:build-and-check
  variables:
    # Setting the default CURRENT_PAGES_URL, in order to make pages work for forks
    # CURRENT_PAGES_URL is set in the canonical project
    CURRENT_PAGES_URL: '$CI_PAGES_URL'
    PAGES_PREFIX: 'svgs'
  script:
    # Move static assets to svgpreviewer directory
    - cp -r dist/ svgpreviewer/static/
    # Build pages site
    - yarn run generate
    - apt-get update
    - apt-get install -y brotli gzip
    # See: https://docs.gitlab.com/ee/user/project/pages/introduction.html#serving-compressed-assets
    - echo "Compressing assets..."
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec gzip --force --keep '{}' \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec brotli --force --keep '{}' \;
    - ls -alth public/
  after_script:
    - echo "Pages accessible through ${CI_ENVIRONMENT_URL}"
  pages:
    publish: packages/gitlab-svgs/public
  artifacts:
    paths:
      - packages/gitlab-svgs/public

svgs:pages:
  extends:
    - .svgs:pages
  pages:
    path_prefix: '$PAGES_PREFIX'
    expire_in: never
  rules:
    - <<: *svgs-is-design-gitlab-com-default-branch

svgs:review-app:
  extends:
    - .svgs:pages
  pages:
    path_prefix: 'review-mr-${CI_MERGE_REQUEST_IID}-${PAGES_PREFIX}'
    expire_in: '2 weeks'
  environment:
    name: '${PAGES_PREFIX}-review/mr-${CI_MERGE_REQUEST_IID}'
    url: '$CURRENT_PAGES_URL'
    auto_stop_in: '2 weeks'
  rules:
    - <<: *svgs-is-design-gitlab-com-mr
