---
globs:
  - '**/*.md'

  # This list should be kept in sync with the exclusions in lefthook.yml.
  - '!.gitlab/**/*.md'
  - '!packages/gitlab-ui/src/vendor/**/*.md'
  - '!pages/components/template.md'
  - '!**/node_modules/**'
  - '!**/CHANGELOG*.md'
config:
  default: true
  line-length: false
  no-inline-html: false
  first-line-heading:
    front_matter_title: 'name'
  no-duplicate-heading:
    siblings_only: true
  no-emphasis-as-heading: false
  descriptive-link-text: false
